plugins {
    id 'com.android.application'
    id 'org.jetbrains.kotlin.android'
    id 'kotlin-kapt'
    id 'kotlin-parcelize'
    id 'com.google.gms.google-services'
    id 'com.google.firebase.crashlytics'
    id 'io.objectbox'
}

android {
    namespace 'com.example.mj_player_tv'
    compileSdk 36

    defaultConfig {
        applicationId "com.example.mj_player_tv"
        minSdk 28
        targetSdk 35
        versionCode 1
        versionName "1.0"
        ndk {
            //noinspection ChromeOsAbiSupport
            abiFilters 'armeabi-v7a', 'arm64-v8a'  // Fügen Sie hier dieselben ABI-Arten hinzu
        }
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
    kotlinOptions {
        jvmTarget = '17'
    }
    viewBinding {
        enabled = true
    }
}

dependencies {

    implementation 'androidx.core:core-ktx:1.16.0'
    implementation 'androidx.leanback:leanback:1.2.0'
    implementation 'androidx.leanback:leanback-preference:1.2.0'

    //Navigation
    implementation "androidx.navigation:navigation-fragment-ktx:2.9.2"
    implementation "androidx.navigation:navigation-ui-ktx:2.9.2"

    // Architectural Components
    implementation "androidx.lifecycle:lifecycle-viewmodel-ktx:2.9.2"

    // Retrofit
    implementation 'com.squareup.retrofit2:retrofit:3.0.0'
    implementation 'com.squareup.retrofit2:converter-gson:3.0.0'
    implementation "com.squareup.okhttp3:logging-interceptor:5.1.0"

    implementation('com.squareup.retrofit2:converter-simplexml:3.0.0') {
        exclude module: 'stax-api'
        exclude module: 'stax'
        exclude module: 'xpp3'
    }

    // Coroutines
    implementation 'org.jetbrains.kotlinx:kotlinx-coroutines-core:1.10.2'
    implementation 'org.jetbrains.kotlinx:kotlinx-coroutines-android:1.10.2'

    implementation'io.coil-kt:coil:2.7.0'

    //ExoPlayer
    implementation "androidx.media3:media3-exoplayer:1.8.0"
    implementation "androidx.media3:media3-ui:1.8.0"
    implementation "androidx.media3:media3-exoplayer-dash:1.8.0"
    implementation "androidx.media3:media3-exoplayer-hls:1.8.0"
    implementation 'androidx.media3:media3-exoplayer-smoothstreaming:1.8.0'
    implementation 'org.jellyfin.media3:media3-ffmpeg-decoder:1.6.1+2'
    implementation 'com.google.android.exoplayer:extension-okhttp:2.19.1'

    //D-Pad Recyclerview
    implementation "com.rubensousa.dpadrecyclerview:dpadrecyclerview:1.4.3"

    //Paging
    implementation 'androidx.paging:paging-runtime-ktx:3.3.6'

    //VLC
    implementation 'org.videolan.android:libvlc-all:3.6.1'

    //Firebase Crashlytics
    //noinspection GradleCompatible
    implementation 'com.google.firebase:firebase-crashlytics:20.0.0'
    implementation 'com.google.firebase:firebase-crashlytics-ndk:20.0.0'
    implementation(platform("com.google.firebase:firebase-bom:34.0.0"))
    implementation 'com.google.firebase:firebase-perf:22.0.0'

    // Sentry
    implementation 'io.sentry:sentry-android:8.17.0'
    implementation 'io.sentry:sentry-android-ndk:8.17.0'

    //Datum-Bearbeitung
    implementation "com.jakewharton.threetenabp:threetenabp:1.4.9"

    //GZ Entpacken
    implementation 'org.apache.commons:commons-compress:1.27.1'

    //XZ Entpacken
    implementation 'org.tukaani:xz:1.10'

    //String-Matching
    implementation 'org.apache.commons:commons-text:1.14.0'
    implementation 'androidx.lifecycle:lifecycle-runtime-android:2.9.2'

    implementation 'androidx.work:work-runtime-ktx:2.10.3'
    implementation'com.google.firebase:firebase-crashlytics-buildtools:3.0.5'
    implementation "androidx.constraintlayout:constraintlayout:2.2.1"
    implementation 'androidx.constraintlayout:constraintlayout-core:1.1.1'
    implementation 'androidx.compose.animation:animation-core-android:1.8.3'

    debugImplementation 'com.squareup.leakcanary:leakcanary-android:2.14'

}