package com.example.mj_player_tv.network.model.plex.items

data class Metadata(
    val Country: List<Country>? = emptyList(),
    val Director: List<Director>? = emptyList(),
    val Genre: List<Genre>? = emptyList(),
    val Image: List<Image>? = emptyList(),
    val Media: List<Media>? = emptyList(),
    val Role: List<Role>? = emptyList(),
    val Writer: List<Writer>? = emptyList(),
    val addedAt: Long? = 0L,
    val audienceRating: Double? = 0.0,
    val chapterSource: String? = "",
    val contentRating: String? = "",
    val duration: Long? = 0L,
    val guid: String? = "",
    val key: String? = "",
    val originalTitle: String? = "",
    val originallyAvailableAt: String? = "",
    val primaryExtraKey: String? = "",
    val ratingKey: String? = "",
    val slug: String? = "",
    val studio: String? = "",
    val summary: String? = "",
    val tagline: String? = "",
    val thumb: String? = "",
    val title: String? = "",
    val type: String? = "",
    val updatedAt: Long? = 0L,
    var viewCount: Int? = 0,
    var viewOffset: Long? = 0L,
    var lastViewedAt: Long? = 0L,
    var leafCount: Int? = 0,
    var viewedLeafCount: Int? = 0,
    val year: Int? = 0,
    var isFavorite: Boolean? = false,
    val art: String = "",
    val childCount: Int? = 0
)